### ISSUE TITLE
Need to remove the namespace

### ISSUE THREAD

**Issue by MarcDBehr** [pozil/streaming-monitor#2]
When trying to create a new scratch org, the following error occurs:

`We don’t recognize this namespace: smon. Did you register it in your Dev Hub org?`

Deleting the namespace definition in the sfdx-project.json file fixes this.

**Comment by pozil** [comment]
Thanks for raising that @MarcDBehr but I do need the namespace to generate the package for AppExchange deployment.
I've removed it from master so that you can create scratch orgs and I've updated the prod deployment script to add it back temporarily when updating the package (see PR #4).
