### ISSUE TITLE
[Feature suggestion] Subscribe to a Custom Channel

### ISSUE THREAD

**Issue by mcdcb** [pozil/streaming-monitor#29]
Love the app! I'm wondering if there's a way to subscribe to a custom event channel (/event/Custom_Name__c) without doing the following:

- Subscribe to a channel
- Event type => Change Data Capture channel
- Delete "/data/" in the Streaming channel field and add your own custom event channel (/event/Custom_Name__c)

Might be worth adding another Event type of "Custom Channel" or something like that?  I'm happy to spin up a PR if you think this would be worthwhile

**Comment by pozil** [comment]
Thanks for the feedback @mcdcb.
I agree that a dropdown would be a nicer UX but I'm not sure whether we can discover the available custom event channels from Apex. We probably need the metadata API for this, right?

**Comment by mcdcb** [comment]
Yeah I don't think we can unfortunately - would another list item for Event Type => Custom Platform Event channel be too hacky? (Essentially cloning the "Change Data Capture channel" behavior since it works for custom Platform Event channels
![Screen Shot 2022-06-23 at 12 21 51 PM](https://user-images.githubusercontent.com/70228750/175380806-ff73bcf2-0b67-4510-bc38-c3de149a9c75.png)
)

**Comment by mcdcb** [comment]
Thanks @pozil !
