### ISSUE TITLE
Display Event Type for PushTopic

### ISSUE THREAD

**Issue by mplunket** [pozil/streaming-monitor#45]
It looks like Event Type is not included in the data displayed for PushTopic events -- would it be possible to include this info to be displayed?

**Comment by pozil** [comment]
Hi @mplunket sorry for the delay. I'm not sure to understand what you're missing.
This is what I see for a PushTopic:
![Screenshot 2024-04-03 at 12 33 00](https://github.com/pozil/streaming-monitor/assets/5071767/269ccd33-0e42-4e3f-aa9e-5a04f1b2bd71)

**Comment by pozil** [comment]
Thanks for the details, I hadn't thought about this but it makes sense.
I just release a [new version](https://github.com/pozil/streaming-monitor/releases/tag/3.13.0) of the app with the event type (see screenshot) for all event types (not just PushTopic).

**Comment by mplunket** [comment]
Awesome - thank you!!
