### ISSUE TITLE
Streaming monitor freeze

### ISSUE THREAD

**Issue by Janny12315** [pozil/streaming-monitor#52]
Can anybody help with that: Streaming monitor freeze. Can not see any type of events 

simple things like restarting computer, change browser did not help
![image](https://github.com/user-attachments/assets/c798f716-9506-4c00-a3f1-27aa830ebeb5)

**Comment by pozil** [comment]
Hi @Janny12315 thanks for reaching. When you say "freezes" do you mean that no events are showing up or that the page is broken and you can't navigate?

Events will only show up in the monitor when they are received. If none ore being sent, then it's normal that the monitor keeps waiting.

**Comment by Janny12315** [comment]
Yes I can't see any events. I tried with different events and different type of subscription - but the same 'waiting for events' message
We have a lot of different events and everybody in my team can see them except me.

**Comment by Janny12315** [comment]
sometimes I can see some of them. But it is rarely. In 95% cases I can't see any events

**Comment by Janny12315** [comment]
and after a while I have this error in console
![image](https://github.com/user-attachments/assets/83fa2feb-8a5d-46b9-a9dc-42b9e40c409b)

**Comment by pozil** [comment]
Thanks for the console screenshot. I have no idea why this happens but it looks like your connection to the streaming API is timing out. Unfortunately, I have no control over this as I'm relying on the base [lightning EMP API component](https://developer.salesforce.com/docs/component-library/bundle/lightning-emp-api/documentation) to subscribe to messages.
I guess that there's a network issue that's causing this. Could it a VPN or a proxy?
