### ISSUE TITLE
feat: subscribe to all CUSTOM streaming events (event types are automatically discovered)

### ISSUE THREAD

**Issue by juanlu-github** [pozil/streaming-monitor#53]
This is a usability improvement.

Currently we have these 2 features:
* Subscribe to all streaming events (event types are automatically discovered).
* Subscribe to and unsubscribe from specific streaming events with a user-friendly UI.

When you have many custom platform events (say 20), subscribing to all of them is always tedious. Either you subscribe to all events and have to manually unsubscribe from all standard platform events (which are a lot and you have to do it one by one) or you manually subscribe to each custom platform event one by one, which is also very time consuming.

Ideally we could have these features:
* Subscribe to all streaming events (event types are automatically discovered).
* Subscribe to all **custom** streaming events (event types are automatically discovered). ==> NEW FEATURE
* Subscribe to and unsubscribe from specific streaming events with a user-friendly UI.

**Comment by pozil** [comment]
Hi @juanlu-github, thanks for the great suggestion. I added this kind of filter in the latest release.
