### ISSUE TITLE
feat: filter by channel type when subscribing to all custom events

### ISSUE THREAD

**Issue by juanlu-interdiscount** [pozil/streaming-monitor#54]
This is a follow-up of https://github.com/pozil/streaming-monitor/issues/53.

When we support to all channels, now we have the ability to apply a filter. Currently the available options are "All events" and "Custom events only". Ideally these options could be fine-tuned, as per the description there are the following "Supported channels: PushTopic, Generic, Platform events, Change Data Capture events and Monitoring events".

The filter options could be:
* All events
* All custom events
* Only PushTopics
* Only Generic Topics
* **Only Platform Events**
* **Only Change Data Capture events**
* Only Monitoring events

Use Case: we have a lot of custom platform events that we test and monitor, but we there also are lots of __ChangeEvent in the system that we are not interested in.

**Comment by pozil** [comment]
Hi @juanlu-interdiscount, I just released a new version with this feature. Enjoy!
